Use the following code to load diabetes datasets, and calculate the pairwise distances between the 1st, 10th, 20th, 50th and 100th samples. Have a comparison on the results of using different metrics (you may pick 3 metrics from the above table).

In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

X_diabetes, y_diabetes = load_diabetes(return_X_y=True)


In [2]:
import numpy as np
from sklearn.datasets import load_diabetes

X_diabetes, y_diabetes = load_diabetes(return_X_y=True)
m,n=X_diabetes.shape
X=np.zeros(5*n).reshape(5,n)
X[0,:]=X_diabetes[1]
X[1,:]=X_diabetes[10]
X[2,:]=X_diabetes[20]
X[3,:]=X_diabetes[50]
X[4,:]=X_diabetes[100]

from sklearn.metrics import DistanceMetric
dist_euclidean = DistanceMetric.get_metric('euclidean')
dist_manhattan = DistanceMetric.get_metric('manhattan')
dist_mahalanobis = DistanceMetric.get_metric('mahalanobis', V=np.cov(X))

print(f'The euclidean pariwise:\n{dist_euclidean.pairwise(X)}')
print(f'The manhattan pariwise:\n{dist_manhattan.pairwise(X)}')
print(f'The mahalanobis pariwise:\n{dist_mahalanobis.pairwise(np.cov(X))}')







The euclidean pariwise:
[[0.         0.19448249 0.15723166 0.15700918 0.19140593]
 [0.19448249 0.         0.13360709 0.18510165 0.29573482]
 [0.15723166 0.13360709 0.         0.11434038 0.18456334]
 [0.15700918 0.18510165 0.11434038 0.         0.16112111]
 [0.19140593 0.29573482 0.18456334 0.16112111 0.        ]]
The manhattan pariwise:
[[0.         0.51621206 0.36885171 0.39942847 0.50072722]
 [0.51621206 0.         0.38323949 0.45747163 0.79488594]
 [0.36885171 0.38323949 0.         0.22044629 0.48609752]
 [0.39942847 0.45747163 0.22044629 0.         0.40407953]
 [0.50072722 0.79488594 0.48609752 0.40407953 0.        ]]
The mahalanobis pariwise:
[[0.         0.05532572 0.05223559 0.05030688 0.04670415]
 [0.05532572 0.         0.03335572 0.03849184 0.06123062]
 [0.05223559 0.03335572 0.         0.03320387 0.03879617]
 [0.05030688 0.03849184 0.03320387 0.         0.0451825 ]
 [0.04670415 0.06123062 0.03879617 0.0451825  0.        ]]


(2) Run a standardization method first and compare the difference with the one by using original data.

In [3]:
import numpy as np
from sklearn.datasets import load_diabetes

X_diabetes, y_diabetes = load_diabetes(return_X_y=True)
m,n=X_diabetes.shape
X=np.zeros(5*n).reshape(5,n)
X[0,:]=X_diabetes[1]
X[1,:]=X_diabetes[10]
X[2,:]=X_diabetes[20]
X[3,:]=X_diabetes[50]
X[4,:]=X_diabetes[100]

from sklearn.metrics import DistanceMetric
dist_manhattan_ori = DistanceMetric.get_metric('manhattan')
print(f'The manhattan pariwise:\n{dist_manhattan.pairwise(X)}')

from sklearn.preprocessing import MinMaxScaler
MinMaxscaler = MinMaxScaler()
MinMaxscaler.fit(X)

dist_manhattan_MinMax = DistanceMetric.get_metric('manhattan')
print(f'The manhattan pariwise:\n{dist_manhattan_MinMax.pairwise(MinMaxscaler.transform(X))}')

from sklearn import preprocessing
import numpy as np
Standardscaler = preprocessing.StandardScaler().fit(X)

dist_manhattan_Standard = DistanceMetric.get_metric('manhattan')
print(f'The manhattan pariwise:\n{dist_manhattan_Standard.pairwise(Standardscaler.transform(X))}')


The manhattan pariwise:
[[0.         0.51621206 0.36885171 0.39942847 0.50072722]
 [0.51621206 0.         0.38323949 0.45747163 0.79488594]
 [0.36885171 0.38323949 0.         0.22044629 0.48609752]
 [0.39942847 0.45747163 0.22044629 0.         0.40407953]
 [0.50072722 0.79488594 0.48609752 0.40407953 0.        ]]
The manhattan pariwise:
[[0.         4.82819315 3.48188114 4.01557297 4.61588308]
 [4.82819315 0.         3.82420743 4.03167432 7.14692428]
 [3.48188114 3.82420743 0.         2.38930218 4.33629151]
 [4.01557297 4.03167432 2.38930218 0.         3.782168  ]
 [4.61588308 7.14692428 4.33629151 3.782168   0.        ]]
The manhattan pariwise:
[[ 0.         13.8004328   9.67618205 11.09975278 13.1925898 ]
 [13.8004328   0.         10.86460071 11.54295849 20.68594153]
 [ 9.67618205 10.86460071  0.          6.50722529 12.53517514]
 [11.09975278 11.54295849  6.50722529  0.         10.9525135 ]
 [13.1925898  20.68594153 12.53517514 10.9525135   0.        ]]
