Distance metrics play important role in machine learning algorithms. Many metrics are implemented in sklearn.Metrics.DistanceMetric package. Please read the following document (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.DistanceMetric.html?highlight=distancemetric#sklearn.metrics.DistanceMetric) so that you know how to call functions to calculate distances between samples.

(1) EuclideanDistance calculation.

In [1]:
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')
X= [[0,1,2],[3,4,5]]
print(dist.pairwise(X))


[[0.         5.19615242]
 [5.19615242 0.        ]]


(1) EuclideanDistance calculation.

In [2]:
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('manhattan')
X= [[0,1,2],[3,4,5]]
print(dist.pairwise(X))

[[0. 9.]
 [9. 0.]]


In [3]:
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('chebyshev')
X= [[0,1,2],[3,4,5]]
print(dist.pairwise(X))

[[0. 3.]
 [3. 0.]]


In [6]:
from sklearn.metrics import DistanceMetric # or from sklearn.metrics import DistanceMetric depending on your version
import numpy as np

X = [[1, 2, 2], [ -1,7, 5]]
V=np.cov(X)

dist = DistanceMetric.get_metric('mahalanobis', V=np.cov(X))
print(dist.pairwise(V))

[[0.         3.60555128]
 [3.60555128 0.        ]]
