In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt


class Net(nn.Module):

    def __init__(self, input_dim=2, out_put_dim=1):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(in_features=input_dim, out_features=2)
        self.fc2 = nn.Linear(in_features=2, out_features=out_put_dim)

    def forward(self, x):

        x = F.relu(self.fc1(x))
        outputs = self.fc2(x)

        return outputs

# --- 实例化一个网络 --- #
my_net = Net()
print("Network:", my_net)
# parameters
for name, params in my_net.named_parameters():
    print(name, params)
print('Total parameters:', sum(param.numel() for param in my_net.parameters()))
# --- optimizer --- #
optimizer = optim.Adam(params=my_net.parameters(), lr=0.01)

# --- data --- #
# Define dataset
data = np.array([
  [-2, -1],  # Alice
  [25, 6],   # Bob
  [17, 4],   # Charlie
  [-15, -6], # Diana
])

all_y_trues = np.array([
  1, # Alice
  0, # Bob
  0, # Charlie
  1, # Diana
])

# --- train --- #
loss_list = list()
for i in range(100):
    # --- （1）数据forward --- #
    sample_index = np.random.randint(0, 4)
    x_train = data[sample_index]
    y_label = all_y_trues[sample_index]
    # numpy to tensor
    x_train = torch.tensor(x_train).to(dtype=torch.float32)
    y_label = torch.tensor(y_label).to(dtype=torch.float32).unsqueeze(dim=0)
    # --- （2）前向传播 --- #
    y_pred = my_net(x_train)
    # --- （3）loss反向传播 --- #
    loss = F.mse_loss(y_pred, y_label)
    # grad zero
    optimizer.zero_grad()
    # back propagation
    loss.backward()
    # update weight
    optimizer.step()
    print('Epoch: %d Loss : %f'%(i, loss.item()))
    loss_list.append(loss.item())


# # --- test --- #
# data_test = np.array([
#   [30, 15]  # Tom
# ])
# x_test = data_test[0]

# # numpy to tensor
# x_test = torch.tensor(x_test).to(dtype=torch.float32)
# y_test_pred = my_net(x_test)
# print(y_test_pred.item())


Network: Net(
  (fc1): Linear(in_features=2, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)
fc1.weight Parameter containing:
tensor([[ 0.6604, -0.1587],
        [ 0.3668,  0.0187]], requires_grad=True)
fc1.bias Parameter containing:
tensor([-0.2831,  0.3743], requires_grad=True)
fc2.weight Parameter containing:
tensor([[-0.1073,  0.0520]], requires_grad=True)
fc2.bias Parameter containing:
tensor([0.0339], requires_grad=True)
Total parameters: 9
Epoch: 0 Loss : 0.524994
Epoch: 1 Loss : 0.914038
Epoch: 2 Loss : 0.131237
Epoch: 3 Loss : 0.120368
Epoch: 4 Loss : 0.861195
Epoch: 5 Loss : 0.017679
Epoch: 6 Loss : 0.830368
Epoch: 7 Loss : 0.815480
Epoch: 8 Loss : 0.799882
Epoch: 9 Loss : 0.475292
Epoch: 10 Loss : 0.427958
Epoch: 11 Loss : 0.765592
Epoch: 12 Loss : 0.756686
Epoch: 13 Loss : 0.746455
Epoch: 14 Loss : 0.735188
Epoch: 15 Loss : 0.723110
Epoch: 16 Loss : 0.035024
Epoch: 17 Loss : 0.020607
Epoch: 18 Loss : 0.690038
Epoch: 19 Loss : 0.679655
